# Generated by Django 6.0 on 2025-12-21 18:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enqueteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('telephone', models.CharField(max_length=15)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_enquete', models.CharField(max_length=20, unique=True, verbose_name="Code d'enquête")),
                ('nom', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('niveau', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('D', 'Doctorat'), ('AUTRE', 'Autre')], max_length=10)),
                ('universite', models.CharField(max_length=100, verbose_name='Établissement')),
                ('quartier', models.CharField(max_length=100)),
                ('gps_lat', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('gps_lng', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('date_collecte', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('COMPLET', 'Complet'), ('VERIFIE', 'Vérifié'), ('ANOMALIE', 'Anomalie détectée')], default='BROUILLON', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name="Observations de l'enquêteur")),
                ('photo', models.ImageField(blank=True, null=True, upload_to='etudiants/', verbose_name='Photo (optionnel)')),
                ('enqueteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.enqueteur', verbose_name='Enquêteur responsable')),
            ],
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('LOGEMENT', 'Logement (loyer, charges)'), ('NOURRITURE', 'Nourriture et boissons'), ('TRANSPORT', 'Transport'), ('SANTE', 'Santé et hygiène'), ('COMMUNICATION', 'Communication (internet, téléphone)'), ('FORMATION', 'Frais académiques'), ('DIVERTISSEMENT', 'Loisirs et divertissement'), ('HABILLEMENT', 'Habillement'), ('AUTRE', 'Autres dépenses')], max_length=20)),
                ('montant', models.FloatField(verbose_name='Montant (FCFA)')),
                ('quartier', models.CharField(max_length=100, verbose_name='Quartier de la dépense')),
                ('lieu_precis', models.CharField(blank=True, max_length=200, verbose_name='Lieu précis (marché, boutique...)')),
                ('date_depense', models.DateField(default=django.utils.timezone.now, verbose_name='Date de la dépense')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='depenses/', verbose_name='Photo du reçu/ticket')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaires')),
                ('est_valide', models.BooleanField(default=True, verbose_name='Donnée valide')),
                ('anomalie', models.TextField(blank=True, verbose_name="Description de l'anomalie")),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('enqueteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.enqueteur')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='core.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Anomalie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_anomalie', models.CharField(choices=[('DOUBLON', 'Donnée en double'), ('HORS_NORME', 'Valeur hors norme'), ('INCOHERENCE', 'Incohérence logique'), ('MANQUANTE', 'Donnée manquante'), ('ERREUR_SAISIE', 'Erreur de saisie')], max_length=20)),
                ('description', models.TextField()),
                ('gravite', models.CharField(choices=[('FAIBLE', 'Faible'), ('MOYENNE', 'Moyenne'), ('ELEVEE', 'Élevée')], max_length=10)),
                ('statut', models.CharField(choices=[('A_TRAITER', 'À traiter'), ('EN_COURS', 'En cours de traitement'), ('RESOLUE', 'Résolue'), ('IGNOREE', 'Ignorée')], default='A_TRAITER', max_length=20)),
                ('date_detection', models.DateTimeField(auto_now_add=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('depense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomalies_depense', to='core.depense')),
                ('enqueteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.enqueteur')),
                ('etudiant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.etudiant')),
            ],
        ),
    ]
